# Generated by Django 2.1.2 on 2018-10-23 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='año',
            new_name='anio',
        ),
    ]
